CREATE TABLE
    IF NOT EXISTS public.neighborhood_report (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint NOT NULL,
        year integer NOT NULL,
        report_timestamp timestamptz NOT NULL,
        neighborhood text,
        address text,
        grade text,
        story text,
        occupancy text,
        cost_group text,
        total_area integer,
        gla integer,
        year_built integer,
        cdu text,
        ea text,
        funct text,
        econ text,
        land integer,
        improve integer,
        prior integer,
        percent_change numeric,
        bldg_source text
    );

COMMENT ON TABLE public.neighborhood_report IS 'Neighborhood report records used for appraisal analysis and review.';

CREATE INDEX IF NOT EXISTS neighborhood_report_parcel_id_idx ON public.neighborhood_report (parcel_id);

CREATE INDEX IF NOT EXISTS neighborhood_report_year_idx ON public.neighborhood_report (year);

CREATE INDEX IF NOT EXISTS neighborhood_report_report_timestamp_idx ON public.neighborhood_report (report_timestamp DESC);

CREATE INDEX IF NOT EXISTS neighborhood_report_neighborhood_idx ON public.neighborhood_report (neighborhood);

CREATE INDEX IF NOT EXISTS neighborhood_report_parcel_year_idx ON public.neighborhood_report (parcel_id, year);

-- Seed app permissions
INSERT INTO
    public.app_permissions (name, description)
VALUES
    (
        'neighborhood_report.read',
        'View neighborhood report records'
    ),
    (
        'neighborhood_report.write',
        'Create and update neighborhood report records'
    ),
    (
        'neighborhood_report.delete',
        'Delete neighborhood report records'
    ) ON CONFLICT (name) DO NOTHING;

-- Seed role permission assignments
-- Admin: full access
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('admin', 'neighborhood_report.read'),
    ('admin', 'neighborhood_report.write'),
    ('admin', 'neighborhood_report.delete') ON CONFLICT (role, permission) DO NOTHING;

-- Manager: read + write
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('manager', 'neighborhood_report.read'),
    ('manager', 'neighborhood_report.write') ON CONFLICT (role, permission) DO NOTHING;

-- Member: read-only
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('member', 'neighborhood_report.read') ON CONFLICT (role, permission) DO NOTHING;

-- Viewer: read-only
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('viewer', 'neighborhood_report.read') ON CONFLICT (role, permission) DO NOTHING;

-- Enable RLS
ALTER TABLE public.neighborhood_report ENABLE ROW LEVEL SECURITY;

CREATE POLICY neighborhood_report_select_policy ON public.neighborhood_report FOR
SELECT
    TO authenticated USING (
        auth.role() = 'service_role'
        OR public.authorize('neighborhood_report.read')
    );

CREATE POLICY neighborhood_report_insert_policy ON public.neighborhood_report FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role() = 'service_role'
        OR public.authorize('neighborhood_report.write')
    );

CREATE POLICY neighborhood_report_update_policy ON public.neighborhood_report FOR
UPDATE TO authenticated USING (
    auth.role() = 'service_role'
    OR public.authorize('neighborhood_report.write')
)
WITH
    CHECK (
        auth.role() = 'service_role'
        OR public.authorize('neighborhood_report.write')
    );

CREATE POLICY neighborhood_report_delete_policy ON public.neighborhood_report FOR DELETE TO authenticated USING (
    auth.role() = 'service_role'
    OR public.authorize('neighborhood_report.delete')
);

CREATE OR REPLACE FUNCTION public.update_neighborhood_report_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_neighborhood_report_updated_at
    BEFORE UPDATE ON public.neighborhood_report
    FOR EACH ROW
    EXECUTE FUNCTION public.update_neighborhood_report_updated_at();