-- Create parcel_detail and parcel_deeds tables with permissions and RLS policies
CREATE TABLE
    IF NOT EXISTS public.parcel_detail (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint NOT NULL,
        legal_id text,
        legal_desc text,
        tax_status text,
        tax_code text,
        use_code text,
        occupancy text,
        class_code text,
        nbhd_group text,
        ward text,
        cda text,
        first_year integer NOT NULL,
        last_year integer NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now (),
        updated_at timestamptz NOT NULL DEFAULT now (),
        CONSTRAINT parcel_detail_year_range_check CHECK (first_year <= last_year)
    );

COMMENT ON TABLE public.parcel_detail IS 'Parcel detail history grouped by parcel attributes with first/last year coverage.';

CREATE INDEX IF NOT EXISTS parcel_detail_parcel_id_idx ON public.parcel_detail (parcel_id);

CREATE INDEX IF NOT EXISTS parcel_detail_first_last_year_idx ON public.parcel_detail (first_year, last_year);

CREATE INDEX IF NOT EXISTS parcel_detail_class_code_idx ON public.parcel_detail (class_code)
WHERE
    class_code IS NOT NULL;

CREATE TABLE
    IF NOT EXISTS public.parcel_deeds (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint NOT NULL,
        deed_book text,
        deed_page text,
        deed_document text,
        deed_date date NOT NULL,
        first_year integer NOT NULL,
        last_year integer NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now (),
        updated_at timestamptz NOT NULL DEFAULT now (),
        CONSTRAINT parcel_deeds_year_range_check CHECK (first_year <= last_year)
    );

COMMENT ON TABLE public.parcel_deeds IS 'Parcel deed history grouped by deed identifiers with first/last year coverage.';

CREATE INDEX IF NOT EXISTS parcel_deeds_parcel_id_idx ON public.parcel_deeds (parcel_id);

CREATE INDEX IF NOT EXISTS parcel_deeds_deed_date_idx ON public.parcel_deeds (deed_date);

CREATE INDEX IF NOT EXISTS parcel_deeds_first_last_year_idx ON public.parcel_deeds (first_year, last_year);

-- Seed app permissions
INSERT INTO
    public.app_permissions (name, description)
VALUES
    (
        'parcel_detail.read',
        'View parcel detail records'
    ),
    (
        'parcel_detail.write',
        'Create and update parcel detail records'
    ),
    (
        'parcel_detail.delete',
        'Delete parcel detail records'
    ),
    ('parcel_deeds.read', 'View parcel deed records'),
    (
        'parcel_deeds.write',
        'Create and update parcel deed records'
    ),
    (
        'parcel_deeds.delete',
        'Delete parcel deed records'
    ) ON CONFLICT (name) DO NOTHING;

-- Seed role permission assignments
-- Admin: full access
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('admin', 'parcel_detail.read'),
    ('admin', 'parcel_detail.write'),
    ('admin', 'parcel_detail.delete'),
    ('admin', 'parcel_deeds.read'),
    ('admin', 'parcel_deeds.write'),
    ('admin', 'parcel_deeds.delete') ON CONFLICT (role, permission) DO NOTHING;

-- Manager: read + write
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('manager', 'parcel_detail.read'),
    ('manager', 'parcel_detail.write'),
    ('manager', 'parcel_deeds.read'),
    ('manager', 'parcel_deeds.write') ON CONFLICT (role, permission) DO NOTHING;

-- Member: read-only
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('member', 'parcel_detail.read'),
    ('member', 'parcel_deeds.read') ON CONFLICT (role, permission) DO NOTHING;

-- Viewer: read-only
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('viewer', 'parcel_detail.read'),
    ('viewer', 'parcel_deeds.read') ON CONFLICT (role, permission) DO NOTHING;

-- Enable RLS
ALTER TABLE public.parcel_detail ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.parcel_deeds ENABLE ROW LEVEL SECURITY;

-- RLS policies for parcel_detail
CREATE POLICY parcel_detail_select_policy ON public.parcel_detail FOR
SELECT
    TO authenticated USING (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_detail.read')
    );

CREATE POLICY parcel_detail_insert_policy ON public.parcel_detail FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_detail.write')
    );

CREATE POLICY parcel_detail_update_policy ON public.parcel_detail FOR
UPDATE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcel_detail.write')
)
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_detail.write')
    );

CREATE POLICY parcel_detail_delete_policy ON public.parcel_detail FOR DELETE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcel_detail.delete')
);

-- RLS policies for parcel_deeds
CREATE POLICY parcel_deeds_select_policy ON public.parcel_deeds FOR
SELECT
    TO authenticated USING (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_deeds.read')
    );

CREATE POLICY parcel_deeds_insert_policy ON public.parcel_deeds FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_deeds.write')
    );

CREATE POLICY parcel_deeds_update_policy ON public.parcel_deeds FOR
UPDATE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcel_deeds.write')
)
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_deeds.write')
    );

CREATE POLICY parcel_deeds_delete_policy ON public.parcel_deeds FOR DELETE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcel_deeds.delete')
);