-- Create neighborhood_summaries table
-- Stores aggregated sales metrics for different neighborhood types and summary types

CREATE TABLE
    IF NOT EXISTS public.neighborhood_summaries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        neighborhood_type TEXT NOT NULL,
        neighborhood_id TEXT NOT NULL,
        summary_type TEXT NOT NULL,
        metrics JSONB NOT NULL,
        computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

-- Create indexes for efficient lookups
CREATE INDEX IF NOT EXISTS neighborhood_summaries_type_idx 
    ON public.neighborhood_summaries (neighborhood_type);

CREATE INDEX IF NOT EXISTS neighborhood_summaries_id_idx 
    ON public.neighborhood_summaries (neighborhood_id);

CREATE INDEX IF NOT EXISTS neighborhood_summaries_summary_type_idx 
    ON public.neighborhood_summaries (summary_type);

CREATE INDEX IF NOT EXISTS neighborhood_summaries_computed_at_idx 
    ON public.neighborhood_summaries (computed_at DESC);

-- Composite index for common lookup pattern
CREATE INDEX IF NOT EXISTS neighborhood_summaries_lookup_idx 
    ON public.neighborhood_summaries (neighborhood_type, neighborhood_id, summary_type);

-- GIN index for JSON metrics queries
CREATE INDEX IF NOT EXISTS neighborhood_summaries_metrics_gin_idx 
    ON public.neighborhood_summaries USING GIN (metrics);


-- Table comments
COMMENT ON TABLE public.neighborhood_summaries IS 'Aggregated sales metrics by neighborhood type (CDA, assessor, commercial cluster, etc.)';

COMMENT ON COLUMN public.neighborhood_summaries.neighborhood_type IS 'Type of neighborhood: cda_neighborhood, assessor_neighborhood, commercial_cluster, building_category, occupancy';

COMMENT ON COLUMN public.neighborhood_summaries.neighborhood_id IS 'Identifier for the specific neighborhood (name, code, or cluster ID)';

COMMENT ON COLUMN public.neighborhood_summaries.summary_type IS 'Type of summary: commercial_sales, residential_sales, residential_ratios, etc.';

COMMENT ON COLUMN public.neighborhood_summaries.metrics IS 'JSON object containing summary statistics (medians, averages, counts)';

COMMENT ON COLUMN public.neighborhood_summaries.computed_at IS 'When the summary metrics were computed from source data';

-- Enable Row Level Security
ALTER TABLE public.neighborhood_summaries ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Read access for authenticated users
CREATE POLICY neighborhood_summaries_select_policy 
    ON public.neighborhood_summaries 
    FOR SELECT 
    TO authenticated 
    USING (public.authorize('neighborhood_summaries.read'));

-- RLS Policy: Insert access for users with write permission
CREATE POLICY neighborhood_summaries_insert_policy 
    ON public.neighborhood_summaries 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (public.authorize('neighborhood_summaries.write'));

-- RLS Policy: Update access for users with write permission
CREATE POLICY neighborhood_summaries_update_policy 
    ON public.neighborhood_summaries 
    FOR UPDATE 
    TO authenticated 
    USING (public.authorize('neighborhood_summaries.write'))
    WITH CHECK (public.authorize('neighborhood_summaries.write'));

-- RLS Policy: Delete access for users with delete permission
CREATE POLICY neighborhood_summaries_delete_policy 
    ON public.neighborhood_summaries 
    FOR DELETE 
    TO authenticated 
    USING (public.authorize('neighborhood_summaries.delete'));

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_neighborhood_summaries_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_neighborhood_summaries_updated_at
    BEFORE UPDATE ON public.neighborhood_summaries
    FOR EACH ROW
    EXECUTE FUNCTION public.update_neighborhood_summaries_updated_at();
