-- Create parcel address relationship tables and seed permissions/RLS policies
CREATE TABLE
    IF NOT EXISTS public.parcel_addresses (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint NOT NULL REFERENCES public.parcels (id) ON DELETE CASCADE,
        address_id text NOT NULL REFERENCES public.addresses_lookup_standardized (address_id) ON DELETE CASCADE,
        unit text,
        is_primary boolean NOT NULL DEFAULT false,
        created_at timestamptz NOT NULL DEFAULT now (),
        updated_at timestamptz NOT NULL DEFAULT now ()
    );

COMMENT ON TABLE public.parcel_addresses IS 'Active parcel-to-address relationships.';

COMMENT ON COLUMN public.parcel_addresses.parcel_id IS 'References parcels.id';

COMMENT ON COLUMN public.parcel_addresses.address_id IS 'References addresses_lookup_standardized.address_id';

COMMENT ON COLUMN public.parcel_addresses.unit IS 'Optional unit/suite for parcel-address mapping.';

COMMENT ON COLUMN public.parcel_addresses.is_primary IS 'Marks the primary address for the parcel.';

-- One primary address per parcel
CREATE UNIQUE INDEX IF NOT EXISTS parcel_addresses_one_primary_idx ON public.parcel_addresses (parcel_id)
WHERE
    is_primary = true;

CREATE INDEX IF NOT EXISTS parcel_addresses_parcel_id_idx ON public.parcel_addresses (parcel_id);

CREATE INDEX IF NOT EXISTS parcel_addresses_address_id_idx ON public.parcel_addresses (address_id);

CREATE TABLE
    IF NOT EXISTS public.retired_parcel_addresses (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint NOT NULL REFERENCES public.parcels (id) ON DELETE CASCADE,
        address_id text NOT NULL REFERENCES public.addresses_lookup_standardized (address_id) ON DELETE CASCADE,
        unit text,
        is_primary boolean NOT NULL DEFAULT false,
        last_year integer NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now (),
        updated_at timestamptz NOT NULL DEFAULT now ()
    );

COMMENT ON TABLE public.retired_parcel_addresses IS 'Historical parcel-to-address relationships for retired parcel records.';

COMMENT ON COLUMN public.retired_parcel_addresses.last_year IS 'Last calendar year this parcel-address relationship was active.';

-- One primary retired address per parcel per year
CREATE UNIQUE INDEX IF NOT EXISTS retired_parcel_addresses_one_primary_idx ON public.retired_parcel_addresses (parcel_id, last_year)
WHERE
    is_primary = true;

CREATE INDEX IF NOT EXISTS retired_parcel_addresses_parcel_id_idx ON public.retired_parcel_addresses (parcel_id);

CREATE INDEX IF NOT EXISTS retired_parcel_addresses_address_id_idx ON public.retired_parcel_addresses (address_id);

CREATE INDEX IF NOT EXISTS retired_parcel_addresses_last_year_idx ON public.retired_parcel_addresses (last_year);

-- Seed app permissions for parcel_addresses and retired_parcel_addresses
INSERT INTO
    public.app_permissions (name, description)
VALUES
    (
        'parcel_addresses.read',
        'View active parcel address relationships'
    ),
    (
        'parcel_addresses.write',
        'Create and update active parcel address relationships'
    ),
    (
        'parcel_addresses.delete',
        'Delete active parcel address relationships'
    ),
    (
        'retired_parcel_addresses.read',
        'View retired parcel address relationships'
    ),
    (
        'retired_parcel_addresses.write',
        'Create and update retired parcel address relationships'
    ),
    (
        'retired_parcel_addresses.delete',
        'Delete retired parcel address relationships'
    ) ON CONFLICT (name) DO NOTHING;

-- Seed role permission assignments
-- Admin: full access
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('admin', 'parcel_addresses.read'),
    ('admin', 'parcel_addresses.write'),
    ('admin', 'parcel_addresses.delete'),
    ('admin', 'retired_parcel_addresses.read'),
    ('admin', 'retired_parcel_addresses.write'),
    ('admin', 'retired_parcel_addresses.delete') ON CONFLICT (role, permission) DO NOTHING;

-- Manager: read + write
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('manager', 'parcel_addresses.read'),
    ('manager', 'parcel_addresses.write'),
    ('manager', 'retired_parcel_addresses.read'),
    ('manager', 'retired_parcel_addresses.write') ON CONFLICT (role, permission) DO NOTHING;

-- Member: read-only
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('member', 'parcel_addresses.read'),
    ('member', 'retired_parcel_addresses.read') ON CONFLICT (role, permission) DO NOTHING;

-- Viewer: read-only
INSERT INTO
    public.role_permissions (role, permission)
VALUES
    ('viewer', 'parcel_addresses.read'),
    ('viewer', 'retired_parcel_addresses.read') ON CONFLICT (role, permission) DO NOTHING;

-- Enable RLS
ALTER TABLE public.parcel_addresses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.retired_parcel_addresses ENABLE ROW LEVEL SECURITY;

-- RLS policies: parcel_addresses
CREATE POLICY parcel_addresses_select_policy ON public.parcel_addresses FOR
SELECT
    TO authenticated USING (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_addresses.read')
    );

CREATE POLICY parcel_addresses_insert_policy ON public.parcel_addresses FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_addresses.write')
    );

CREATE POLICY parcel_addresses_update_policy ON public.parcel_addresses FOR
UPDATE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcel_addresses.write')
)
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcel_addresses.write')
    );

CREATE POLICY parcel_addresses_delete_policy ON public.parcel_addresses FOR DELETE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcel_addresses.delete')
);

-- RLS policies: retired_parcel_addresses
CREATE POLICY retired_parcel_addresses_select_policy ON public.retired_parcel_addresses FOR
SELECT
    TO authenticated USING (
        auth.role () = 'service_role'
        OR public.authorize ('retired_parcel_addresses.read')
    );

CREATE POLICY retired_parcel_addresses_insert_policy ON public.retired_parcel_addresses FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('retired_parcel_addresses.write')
    );

CREATE POLICY retired_parcel_addresses_update_policy ON public.retired_parcel_addresses FOR
UPDATE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('retired_parcel_addresses.write')
)
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('retired_parcel_addresses.write')
    );

CREATE POLICY retired_parcel_addresses_delete_policy ON public.retired_parcel_addresses FOR DELETE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('retired_parcel_addresses.delete')
);