-- Create assessments table for parcel assessment records
CREATE TABLE
    IF NOT EXISTS public.assessments (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint REFERENCES public.parcels (id) ON DELETE SET NULL,
        category text,
        date_of_assessment timestamptz,
        last_changed date,
        changed_by text,
        app_bldg_agriculture integer,
        app_bldg_commercial integer,
        app_bldg_residential integer,
        app_bldg_exempt integer,
        app_land_agriculture integer,
        app_land_commercial integer,
        app_land_residential integer,
        app_land_exempt integer,
        app_new_const_agriculture integer,
        app_new_const_commercial integer,
        app_new_const_residential integer,
        app_new_const_exempt integer,
        bldg_agriculture integer,
        bldg_commercial integer,
        bldg_residential integer,
        bldg_exempt integer,
        land_agriculture integer,
        land_commercial integer,
        land_residential integer,
        land_exempt integer,
        new_const_agriculture integer,
        new_const_commercial integer,
        new_const_residential integer,
        new_const_exempt integer,
        report_timestamp timestamptz,
        hash_id text,
        change_reason text
    );

COMMENT ON TABLE public.assessments IS 'Assessment values and change metadata for parcels.';

COMMENT ON COLUMN public.assessments.parcel_id IS 'Reference to parcels table.';

COMMENT ON COLUMN public.assessments.category IS 'Assessment category.';

COMMENT ON COLUMN public.assessments.date_of_assessment IS 'Date/time the assessment was performed.';

COMMENT ON COLUMN public.assessments.last_changed IS 'Date of last change.';

COMMENT ON COLUMN public.assessments.changed_by IS 'User or system that made the change.';

COMMENT ON COLUMN public.assessments.report_timestamp IS 'Timestamp for reporting exports.';

COMMENT ON COLUMN public.assessments.hash_id IS 'External hash identifier for assessment records.';

COMMENT ON COLUMN public.assessments.change_reason IS 'Reason for assessment change.';

-- Indexes for common lookup and filtering patterns
CREATE INDEX assessments_parcel_id_idx ON public.assessments (parcel_id)
WHERE
    parcel_id IS NOT NULL;

CREATE INDEX assessments_date_of_assessment_idx ON public.assessments (date_of_assessment)
WHERE
    date_of_assessment IS NOT NULL;

CREATE INDEX assessments_report_timestamp_idx ON public.assessments (report_timestamp)
WHERE
    report_timestamp IS NOT NULL;

CREATE INDEX assessments_hash_id_idx ON public.assessments (hash_id)
WHERE
    hash_id IS NOT NULL;

CREATE INDEX assessments_category_idx ON public.assessments (category)
WHERE
    category IS NOT NULL;

-- Enable RLS
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;

-- Read: users can see assessments if they have assessments.read permission
CREATE POLICY assessments_select_authorized ON public.assessments FOR
SELECT
    TO authenticated USING (
        auth.role () = 'service_role'
        OR public.authorize ('assessments.read')
    );

-- Write: users can insert/update assessments if they have assessments.write permission
CREATE POLICY assessments_insert_authorized ON public.assessments FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('assessments.write')
    );

CREATE POLICY assessments_update_authorized ON public.assessments FOR
UPDATE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('assessments.write')
)
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('assessments.write')
    );

-- Delete: users can delete assessments if they have assessments.delete permission
CREATE POLICY assessments_delete_authorized ON public.assessments FOR DELETE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('assessments.delete')
);

-- Grant minimal permissions per security-least-privilege best practice
GRANT USAGE ON SCHEMA public TO authenticated;

GRANT
SELECT
    ON public.assessments TO authenticated;