CREATE TABLE
	IF NOT EXISTS public.parcel_primary_site_address_history (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		parcel_id bigint NOT NULL,
		address_id text NOT NULL,
		devnet_address text,
		tiger_address text,
		geom geometry (Point, 4326),
		last_year integer NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now (),
		updated_at timestamptz NOT NULL DEFAULT now (),
		CONSTRAINT parcel_primary_site_address_history_parcel_last_year_unique UNIQUE (parcel_id, last_year)
	);

COMMENT ON TABLE public.parcel_primary_site_address_history IS 'Historical primary site address rows per parcel by last active year.';

COMMENT ON COLUMN public.parcel_primary_site_address_history.devnet_address IS 'Source devnet full address text from parcel mapping export.';

COMMENT ON COLUMN public.parcel_primary_site_address_history.tiger_address IS 'Raw address text from tigerline/geocoder lookup.';

COMMENT ON COLUMN public.parcel_primary_site_address_history.last_year IS 'Last calendar year this primary parcel site address row was active.';

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_history_parcel_id_idx ON public.parcel_primary_site_address_history (parcel_id);

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_history_address_id_idx ON public.parcel_primary_site_address_history (address_id);

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_history_last_year_idx ON public.parcel_primary_site_address_history (last_year);

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_history_geom_idx ON public.parcel_primary_site_address_history USING GIST (geom)
WHERE
	geom IS NOT NULL;

-- Seed app permissions
INSERT INTO
	public.app_permissions (name, description)
VALUES
	(
		'parcel_primary_site_address_history.read',
		'View historical primary parcel site addresses'
	),
	(
		'parcel_primary_site_address_history.write',
		'Create and update historical primary parcel site addresses'
	),
	(
		'parcel_primary_site_address_history.delete',
		'Delete historical primary parcel site addresses'
	) ON CONFLICT (name) DO NOTHING;

-- Seed role permission assignments
-- Admin: full access
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('admin', 'parcel_primary_site_address_history.read'),
	('admin', 'parcel_primary_site_address_history.write'),
	('admin', 'parcel_primary_site_address_history.delete') ON CONFLICT (role, permission) DO NOTHING;

-- Manager: read + write
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('manager', 'parcel_primary_site_address_history.read'),
	('manager', 'parcel_primary_site_address_history.write') ON CONFLICT (role, permission) DO NOTHING;

-- Member: read-only
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('member', 'parcel_primary_site_address_history.read') ON CONFLICT (role, permission) DO NOTHING;

-- Viewer: read-only
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('viewer', 'parcel_primary_site_address_history.read') ON CONFLICT (role, permission) DO NOTHING;

-- Enable RLS
ALTER TABLE public.parcel_primary_site_address_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY parcel_primary_site_address_history_select_policy ON public.parcel_primary_site_address_history FOR
SELECT
	TO authenticated USING (
		public.authorize ('parcel_primary_site_address_history.read')
	);

CREATE POLICY parcel_primary_site_address_history_insert_policy ON public.parcel_primary_site_address_history FOR INSERT TO authenticated
WITH
	CHECK (
		public.authorize ('parcel_primary_site_address_history.write')
	);

CREATE POLICY parcel_primary_site_address_history_update_policy ON public.parcel_primary_site_address_history FOR
UPDATE TO authenticated USING (
	public.authorize ('parcel_primary_site_address_history.write')
)
WITH
	CHECK (
		public.authorize ('parcel_primary_site_address_history.write')
	);

CREATE POLICY parcel_primary_site_address_history_delete_policy ON public.parcel_primary_site_address_history FOR DELETE TO authenticated USING (
	public.authorize ('parcel_primary_site_address_history.delete')
);

CREATE OR REPLACE FUNCTION public.update_parcel_primary_site_address_history_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_parcel_primary_site_address_history_updated_at
	BEFORE UPDATE ON public.parcel_primary_site_address_history
	FOR EACH ROW
	EXECUTE FUNCTION public.update_parcel_primary_site_address_history_updated_at();
