-- Create cda_neighborhoods table with PostGIS geometry
CREATE TABLE
    IF NOT EXISTS public.cda_neighborhoods (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        "group" text,
        geom geometry (Polygon, 4326) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now ()
    );

-- Create indexes
CREATE INDEX IF NOT EXISTS cda_neighborhoods_geom_idx ON public.cda_neighborhoods USING GIST (geom);

COMMENT ON TABLE public.cda_neighborhoods IS 'CDA Neighborhoods with PostGIS geometry polygons in WGS84 (EPSG:4326)';

COMMENT ON COLUMN public.cda_neighborhoods.geom IS 'Polygon geometry in WGS84 (lat/lng)';

-- Enable RLS
ALTER TABLE public.cda_neighborhoods ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view all neighborhoods
CREATE POLICY "Users can view cda neighborhoods" ON public.cda_neighborhoods FOR
SELECT
    TO authenticated USING (true);

-- RLS Policy: Only users with cda_neighborhoods.manage can insert/update/delete neighborhoods
CREATE POLICY "Only users with cda_neighborhoods.manage can modify neighborhoods" ON public.cda_neighborhoods FOR ALL TO authenticated USING (authorize ('cda_neighborhoods.manage'))
WITH
    CHECK (authorize ('cda_neighborhoods.manage'));