-- Create parcels table with optimized indexes
-- Based on Postgres best practices: query-missing-indexes, schema-partial-indexes, schema-composite-indexes
CREATE TABLE
    IF NOT EXISTS public.parcels (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        block integer NULL,
        lot integer NULL,
        ext integer NULL,
        parcel_number text NULL, -- optional human-friendly id
        created_at timestamptz NOT NULL DEFAULT now (),
        retired_at timestamptz NULL
    );

-- Index 1: Composite index on (block, lot, ext) for multi-column parcel lookups
-- Purpose: Most parcel lookups filter by block, lot, and ext together
-- Impact: 5-10x faster multi-column queries per schema-composite-indexes best practice
-- Column order: block (=), lot (=), ext (=) - all equality filters
CREATE INDEX parcels_block_lot_ext_idx ON public.parcels (block, lot, ext)
WHERE
    retired_at IS NULL;

-- Index 2: Partial index on parcel_number for human-friendly lookups
-- Purpose: Queries frequently search by parcel_number on active records
-- Impact: 5-20x smaller index and faster queries per schema-partial-indexes best practice
-- Only includes non-retired parcels since lookups are typically for active data
CREATE INDEX parcels_parcel_number_idx ON public.parcels (parcel_number)
WHERE
    retired_at IS NULL
    AND parcel_number IS NOT NULL;

-- Index 3: Partial index on created_at for time-series queries
-- Purpose: Time-based filtering on active parcels (audits, exports, date ranges)
-- Impact: Smaller, faster index by excluding retired records
-- Useful for queries like: WHERE created_at > '2024-01-01' AND retired_at IS NULL
CREATE INDEX parcels_created_at_idx ON public.parcels (created_at)
WHERE
    retired_at IS NULL;

-- Index 4: Partial index for soft-delete pattern
-- Purpose: Optimizes the very common filter: WHERE retired_at IS NULL
-- Impact: Queries for active parcels are 5-20x faster per schema-partial-indexes best practice
-- This is a covering index pattern - includes all columns needed for typical list queries
CREATE INDEX parcels_active_idx ON public.parcels (block, lot, ext)
WHERE
    retired_at IS NULL;

-- Optional: If needed for looking up by ID + active status
-- CREATE INDEX parcels_id_active_idx ON public.parcels (id)
-- WHERE retired_at IS NULL;
-- Row Level Security for parcels with permission-based authorization
ALTER TABLE public.parcels ENABLE ROW LEVEL SECURITY;

-- Read: users can see parcels if they have parcels.read permission
CREATE POLICY parcels_select_authorized ON public.parcels FOR
SELECT
    TO authenticated USING (
        auth.role () = 'service_role'
        OR public.authorize ('parcels.read')
    );

-- Write: users can insert/update parcels if they have parcels.write permission
CREATE POLICY parcels_insert_authorized ON public.parcels FOR INSERT TO authenticated
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcels.write')
    );

CREATE POLICY parcels_update_authorized ON public.parcels FOR
UPDATE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcels.write')
)
WITH
    CHECK (
        auth.role () = 'service_role'
        OR public.authorize ('parcels.write')
    );

-- Delete: users can delete parcels if they have parcels.delete permission
CREATE POLICY parcels_delete_authorized ON public.parcels FOR DELETE TO authenticated USING (
    auth.role () = 'service_role'
    OR public.authorize ('parcels.delete')
);

-- Grant minimal permissions per security-least-privilege best practice
GRANT USAGE ON SCHEMA public TO authenticated;

GRANT
SELECT
    ON public.parcels TO authenticated;