-- Create addresses table for building/street address data
CREATE TABLE
    IF NOT EXISTS public.addresses (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hash text UNIQUE NOT NULL,
        number text,
        street text NOT NULL,
        unit text,
        city text,
        district text,
        region text,
        postcode text,
        openaddresses_id text,
        accuracy text,
        geom geometry (Point, 4326) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now ()
    );

COMMENT ON TABLE public.addresses IS 'Street addresses with point geometry (WGS84)';

COMMENT ON COLUMN public.addresses.hash IS 'Unique hash identifier for address';

COMMENT ON COLUMN public.addresses.number IS 'Street number';

COMMENT ON COLUMN public.addresses.street IS 'Street name';

COMMENT ON COLUMN public.addresses.unit IS 'Unit/apartment number';

COMMENT ON COLUMN public.addresses.city IS 'City name';

COMMENT ON COLUMN public.addresses.district IS 'District or neighborhood';

COMMENT ON COLUMN public.addresses.region IS 'Region or state';

COMMENT ON COLUMN public.addresses.postcode IS 'Postal code/ZIP code';

COMMENT ON COLUMN public.addresses.openaddresses_id IS 'OpenAddresses.io ID';

COMMENT ON COLUMN public.addresses.accuracy IS 'Address accuracy indicator';

COMMENT ON COLUMN public.addresses.geom IS 'Point geometry in WGS84 latitude/longitude';

-- Create spatial index for point queries
CREATE INDEX addresses_geom_idx ON public.addresses USING GIST (geom);

COMMENT ON INDEX public.addresses_geom_idx IS 'Spatial index for proximity and intersection queries';

-- Create indexes for common searches
CREATE INDEX addresses_street_idx ON public.addresses (street)
WHERE
    street IS NOT NULL;

CREATE INDEX addresses_postcode_idx ON public.addresses (postcode)
WHERE
    postcode IS NOT NULL;

CREATE INDEX addresses_hash_idx ON public.addresses (hash);

-- Enable RLS
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view all addresses
CREATE POLICY "Users can view addresses" ON public.addresses FOR
SELECT
    TO authenticated USING (true);

-- RLS Policy: Only users with addresses.manage can insert/update/delete addresses
CREATE POLICY "Only users with addresses.manage can modify addresses" ON public.addresses FOR ALL TO authenticated USING (authorize ('addresses.manage'))
WITH
    CHECK (authorize ('addresses.manage'));