-- Create staging + standardized address lookup tables and a DB function to standardize addresses

-- Ensure required extensions are available
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS address_standardizer;
CREATE EXTENSION IF NOT EXISTS address_standardizer_data_us;

-- Staging table for dataframe loads from R
-- Keep tigerline columns nullable for non-tiger sourced addresses.
CREATE TABLE IF NOT EXISTS public.addresses_lookup_temp (
    address_id text PRIMARY KEY,
    tigerline_id text,
    tigerline_id_side text,
    raw_address text NOT NULL,
    geom geometry(Point, 4326),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.addresses_lookup_temp IS 'Staging table for geocoded address lookup rows loaded from R.';
COMMENT ON COLUMN public.addresses_lookup_temp.address_id IS 'Source address identifier from lookup dataframe.';
COMMENT ON COLUMN public.addresses_lookup_temp.tigerline_id IS 'Optional tigerline identifier; nullable for non-tiger sourced rows.';
COMMENT ON COLUMN public.addresses_lookup_temp.tigerline_id_side IS 'Optional side-of-street from tigerline data (for example L or R).';
COMMENT ON COLUMN public.addresses_lookup_temp.raw_address IS 'Original address string used for standardization.';
COMMENT ON COLUMN public.addresses_lookup_temp.geom IS 'Point geometry in WGS84 (EPSG:4326).';

CREATE INDEX IF NOT EXISTS addresses_lookup_temp_geom_idx
    ON public.addresses_lookup_temp USING GIST (geom)
    WHERE geom IS NOT NULL;

CREATE INDEX IF NOT EXISTS addresses_lookup_temp_tigerline_id_idx
    ON public.addresses_lookup_temp (tigerline_id)
    WHERE tigerline_id IS NOT NULL;

-- Destination table for standardized addresses.
CREATE TABLE IF NOT EXISTS public.addresses_lookup_standardized (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_id text UNIQUE NOT NULL,
    tigerline_id text,
    tigerline_id_side text,
    raw_address text NOT NULL,
    std_building text,
    std_house_num text,
    std_predir text,
    std_qual text,
    std_pretype text,
    std_name text,
    std_suftype text,
    std_sufdir text,
    std_ruralroute text,
    std_extra text,
    std_city text,
    std_state text,
    std_country text,
    std_postcode text,
    std_box text,
    std_unit text,
    geom geometry(Point, 4326),
    standardized_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.addresses_lookup_standardized IS 'Standardized addresses derived from addresses_lookup_temp via address_standardizer.';
COMMENT ON COLUMN public.addresses_lookup_standardized.address_id IS 'Source address identifier from staging table.';
COMMENT ON COLUMN public.addresses_lookup_standardized.raw_address IS 'Original source address string before standardization.';
COMMENT ON COLUMN public.addresses_lookup_standardized.geom IS 'Point geometry preserved from staging in WGS84 (EPSG:4326).';

CREATE INDEX IF NOT EXISTS addresses_lookup_standardized_geom_idx
    ON public.addresses_lookup_standardized USING GIST (geom)
    WHERE geom IS NOT NULL;

CREATE INDEX IF NOT EXISTS addresses_lookup_standardized_tigerline_id_idx
    ON public.addresses_lookup_standardized (tigerline_id)
    WHERE tigerline_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS addresses_lookup_standardized_std_name_idx
    ON public.addresses_lookup_standardized (std_name)
    WHERE std_name IS NOT NULL;

-- Standardize all rows from staging into destination using one set-based query.
-- Existing standardized rows (same address_id) are skipped.
CREATE OR REPLACE FUNCTION public.standardize_addresses_lookup_temp(
    p_truncate_destination boolean DEFAULT false
)
RETURNS TABLE (
    processed_count integer,
    inserted_count integer,
    updated_count integer
)
AS $$
BEGIN
    IF p_truncate_destination THEN
        TRUNCATE TABLE public.addresses_lookup_standardized RESTART IDENTITY;
    END IF;

    WITH src AS (
        SELECT
            t.address_id,
            t.tigerline_id,
            t.tigerline_id_side,
            t.raw_address,
            t.geom,
            standardize_address('us_lex', 'us_gaz', 'us_rules', t.raw_address) AS std
        FROM public.addresses_lookup_temp t
        WHERE NOT EXISTS (
            SELECT 1
            FROM public.addresses_lookup_standardized s
            WHERE s.address_id = t.address_id
        )
    ),
    upserted AS (
        INSERT INTO public.addresses_lookup_standardized (
            address_id,
            tigerline_id,
            tigerline_id_side,
            raw_address,
            std_building,
            std_house_num,
            std_predir,
            std_qual,
            std_pretype,
            std_name,
            std_suftype,
            std_sufdir,
            std_ruralroute,
            std_extra,
            std_city,
            std_state,
            std_country,
            std_postcode,
            std_box,
            std_unit,
            geom,
            standardized_at,
            updated_at
        )
        SELECT
            s.address_id,
            s.tigerline_id,
            s.tigerline_id_side,
            s.raw_address,
            (s.std).building,
            CASE
                WHEN (s.std).predir IS NULL
                    AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                THEN regexp_replace((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$', '')
                ELSE (s.std).house_num
            END,
            CASE
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'N' THEN 'NORTH'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'S' THEN 'SOUTH'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'E' THEN 'EAST'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'W' THEN 'WEST'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'NE' THEN 'NORTHEAST'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'NW' THEN 'NORTHWEST'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'SE' THEN 'SOUTHEAST'
                WHEN UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                ) = 'SW' THEN 'SOUTHWEST'
                ELSE UPPER(
                    CASE
                        WHEN (s.std).predir IS NULL
                            AND (s.std).house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$'
                        THEN (regexp_match((s.std).house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
                        ELSE (s.std).predir
                    END
                )
            END,
            (s.std).qual,
            (s.std).pretype,
            (s.std).name,
            (s.std).suftype,
            (s.std).sufdir,
            (s.std).ruralroute,
            (s.std).extra,
            (s.std).city,
            (s.std).state,
            (s.std).country,
            (s.std).postcode,
            (s.std).box,
            (s.std).unit,
            s.geom,
            now(),
            now()
        FROM src s
        ON CONFLICT (address_id) DO NOTHING
        RETURNING (xmax = 0) AS was_inserted
    )
    SELECT
        (SELECT COUNT(*) FROM src),
        COUNT(*) FILTER (WHERE was_inserted),
        COUNT(*) FILTER (WHERE NOT was_inserted)
    INTO processed_count, inserted_count, updated_count
    FROM upserted;

    -- Normalize directional suffixes that were parsed into house_num instead of predir.
    -- This also fixes rows standardized in previous runs without re-running standardizer.
    UPDATE public.addresses_lookup_standardized a
    SET
        std_house_num = regexp_replace(a.std_house_num, ' (N|S|E|W|NE|NW|SE|SW)$', ''),
        std_predir = CASE (regexp_match(a.std_house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
            WHEN 'N' THEN 'NORTH'
            WHEN 'S' THEN 'SOUTH'
            WHEN 'E' THEN 'EAST'
            WHEN 'W' THEN 'WEST'
            WHEN 'NE' THEN 'NORTHEAST'
            WHEN 'NW' THEN 'NORTHWEST'
            WHEN 'SE' THEN 'SOUTHEAST'
            WHEN 'SW' THEN 'SOUTHWEST'
            ELSE (regexp_match(a.std_house_num, ' (N|S|E|W|NE|NW|SE|SW)$'))[1]
        END,
        updated_at = now()
    WHERE a.std_predir IS NULL
        AND a.std_house_num ~ ' (N|S|E|W|NE|NW|SE|SW)$';

    -- Normalize existing abbreviated predir values to full direction words.
    UPDATE public.addresses_lookup_standardized a
    SET
        std_predir = CASE UPPER(a.std_predir)
            WHEN 'N' THEN 'NORTH'
            WHEN 'S' THEN 'SOUTH'
            WHEN 'E' THEN 'EAST'
            WHEN 'W' THEN 'WEST'
            WHEN 'NE' THEN 'NORTHEAST'
            WHEN 'NW' THEN 'NORTHWEST'
            WHEN 'SE' THEN 'SOUTHEAST'
            WHEN 'SW' THEN 'SOUTHWEST'
            ELSE UPPER(a.std_predir)
        END,
        updated_at = now()
    WHERE a.std_predir IS NOT NULL;

    IF processed_count IS NULL THEN
        processed_count := 0;
        inserted_count := 0;
        updated_count := 0;
    END IF;

    RETURN QUERY
    SELECT processed_count, inserted_count, updated_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.standardize_addresses_lookup_temp IS 'Standardize rows from addresses_lookup_temp into addresses_lookup_standardized using address_standardizer and preserve geometry/tigerline values.';
