CREATE TABLE
	IF NOT EXISTS public.parcel_primary_site_address_current (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		parcel_id bigint NOT NULL,
		address_id text NOT NULL,
		devnet_address text,
		tiger_address text,
		geom geometry (Point, 4326),
		created_at timestamptz NOT NULL DEFAULT now (),
		updated_at timestamptz NOT NULL DEFAULT now (),
		CONSTRAINT parcel_primary_site_address_current_parcel_unique UNIQUE (parcel_id)
	);

COMMENT ON TABLE public.parcel_primary_site_address_current IS 'Current primary site address per parcel, joined from parcel/site mapping and address lookup.';

COMMENT ON COLUMN public.parcel_primary_site_address_current.devnet_address IS 'Source devnet full address text from parcel mapping export.';

COMMENT ON COLUMN public.parcel_primary_site_address_current.tiger_address IS 'Raw address text from tigerline/geocoder lookup.';

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_current_parcel_id_idx ON public.parcel_primary_site_address_current (parcel_id);

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_current_address_id_idx ON public.parcel_primary_site_address_current (address_id);

CREATE INDEX IF NOT EXISTS parcel_primary_site_address_current_geom_idx ON public.parcel_primary_site_address_current USING GIST (geom)
WHERE
	geom IS NOT NULL;

-- Seed app permissions
INSERT INTO
	public.app_permissions (name, description)
VALUES
	(
		'parcel_primary_site_address_current.read',
		'View current primary parcel site addresses'
	),
	(
		'parcel_primary_site_address_current.write',
		'Create and update current primary parcel site addresses'
	),
	(
		'parcel_primary_site_address_current.delete',
		'Delete current primary parcel site addresses'
	) ON CONFLICT (name) DO NOTHING;

-- Seed role permission assignments
-- Admin: full access
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('admin', 'parcel_primary_site_address_current.read'),
	('admin', 'parcel_primary_site_address_current.write'),
	('admin', 'parcel_primary_site_address_current.delete') ON CONFLICT (role, permission) DO NOTHING;

-- Manager: read + write
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('manager', 'parcel_primary_site_address_current.read'),
	('manager', 'parcel_primary_site_address_current.write') ON CONFLICT (role, permission) DO NOTHING;

-- Member: read-only
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('member', 'parcel_primary_site_address_current.read') ON CONFLICT (role, permission) DO NOTHING;

-- Viewer: read-only
INSERT INTO
	public.role_permissions (role, permission)
VALUES
	('viewer', 'parcel_primary_site_address_current.read') ON CONFLICT (role, permission) DO NOTHING;

-- Enable RLS
ALTER TABLE public.parcel_primary_site_address_current ENABLE ROW LEVEL SECURITY;

CREATE POLICY parcel_primary_site_address_current_select_policy ON public.parcel_primary_site_address_current FOR
SELECT
	TO authenticated USING (
		public.authorize ('parcel_primary_site_address_current.read')
	);

CREATE POLICY parcel_primary_site_address_current_insert_policy ON public.parcel_primary_site_address_current FOR INSERT TO authenticated
WITH
	CHECK (
		public.authorize ('parcel_primary_site_address_current.write')
	);

CREATE POLICY parcel_primary_site_address_current_update_policy ON public.parcel_primary_site_address_current FOR
UPDATE TO authenticated USING (
	public.authorize ('parcel_primary_site_address_current.write')
)
WITH
	CHECK (
		public.authorize ('parcel_primary_site_address_current.write')
	);

CREATE POLICY parcel_primary_site_address_current_delete_policy ON public.parcel_primary_site_address_current FOR DELETE TO authenticated USING (
	public.authorize ('parcel_primary_site_address_current.delete')
);

CREATE OR REPLACE FUNCTION public.update_parcel_primary_site_address_current_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_parcel_primary_site_address_current_updated_at
	BEFORE UPDATE ON public.parcel_primary_site_address_current
	FOR EACH ROW
	EXECUTE FUNCTION public.update_parcel_primary_site_address_current_updated_at();
