-- Create wards table with PostGIS geometry
CREATE TABLE
    IF NOT EXISTS public.wards (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        "group" text,
        geom geometry (Polygon, 4326) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now ()
    );

-- Create indexes
CREATE INDEX IF NOT EXISTS wards_geom_idx ON public.wards USING GIST (geom);

COMMENT ON TABLE public.wards IS 'City Wards with PostGIS geometry polygons in WGS84 (EPSG:4326)';

COMMENT ON COLUMN public.wards.geom IS 'Polygon geometry in WGS84 (lat/lng)';

-- Enable RLS
ALTER TABLE public.wards ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view all wards
CREATE POLICY "Users can view wards" ON public.wards FOR
SELECT
    TO authenticated USING (true);

-- RLS Policy: Only users with wards.manage can insert/update/delete wards
CREATE POLICY "Only users with wards.manage can modify wards" ON public.wards FOR ALL TO authenticated USING (authorize ('wards.manage'))
WITH
    CHECK (authorize ('wards.manage'));