-- Enable PostGIS extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- Create geometries table to store parcel geometries
CREATE TABLE
    IF NOT EXISTS public.geometries (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id bigint NOT NULL UNIQUE REFERENCES public.parcels (id) ON DELETE CASCADE,
        parcel_number text NULL,
        geom geometry (MultiPolygon, 4326) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now (),
        updated_at timestamptz NOT NULL DEFAULT now ()
    );

COMMENT ON TABLE public.geometries IS 'Stores PostGIS geometries for parcels in WGS84 (EPSG:4326)';

COMMENT ON COLUMN public.geometries.parcel_id IS 'Foreign key reference to parcels table';

COMMENT ON COLUMN public.geometries.geom IS 'MultiPolygon geometry in WGS84 latitude/longitude';

-- Create spatial index for fast geometric queries
-- GIST index optimized for spatial operations like intersection, contains, distance
CREATE INDEX geometries_geom_idx ON public.geometries USING GIST (geom);

COMMENT ON INDEX public.geometries_geom_idx IS 'Spatial index for geometric queries (intersection, contains, distance, etc.)';

-- Create index for foreign key
CREATE INDEX geometries_parcel_id_idx ON public.geometries (parcel_id);

-- Enable RLS
ALTER TABLE public.geometries ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view geometries for parcels they have permission to access
-- This assumes you have a permission system set up via the app_roles/app_permissions tables
CREATE POLICY "Users can view geometries for permitted parcels" ON public.geometries FOR
SELECT
    TO authenticated USING (true);

-- RLS Policy: Only users with geometries.manage permission can insert/update/delete geometries
CREATE POLICY "Only users with geometries.manage can modify geometries" ON public.geometries FOR ALL TO authenticated USING (authorize ('geometries.manage'))
WITH
    CHECK (authorize ('geometries.manage'));