-- Create parcel_search_table for geocoded parcel data
-- This table stores comprehensive parcel information including addresses, ownership, assessments, and building details
CREATE TABLE
    IF NOT EXISTS public.parcel_search_table (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parcel_id numeric NULL,
        collector_parcel_id text NULL,
        low_address_number integer NULL,
        low_address_suffix text NULL,
        high_address_number integer NULL,
        high_address_suffix text NULL,
        street_prefix_direction text NULL,
        street_name text NULL,
        street_type text NULL,
        std_unit_number text NULL,
        zip text NULL,
        owner_name text NULL,
        owner_name_2 text NULL,
        owner_address text NULL,
        owner_city text NULL,
        owner_state text NULL,
        owner_zip text NULL,
        owner_country text NULL,
        geo_handle text NULL,
        class_code numeric NULL,
        occupancy text NULL,
        abatement_type text NULL,
        abatement_start_year numeric NULL,
        abatement_end_year numeric NULL,
        sbd_district_1 text NULL,
        sbd_district_2 text NULL,
        sbd_district_3 text NULL,
        tif_district text NULL,
        land_area integer NULL,
        assessed_land integer NULL,
        assessed_improvements integer NULL,
        assessed_total integer NULL,
        assessed_res_land integer NULL,
        assessed_com_land integer NULL,
        assessed_agr_land integer NULL,
        assessed_res_improvements integer NULL,
        assessed_com_improvements integer NULL,
        assessed_agr_improvements integer NULL,
        appraised_land integer NULL,
        appraised_res_land integer NULL,
        appraised_com_land integer NULL,
        appraised_agr_land integer NULL,
        appraised_res_improvements integer NULL,
        appraised_com_improvements integer NULL,
        appraised_agr_improvements integer NULL,
        ward text NULL,
        cda_neighborhood text NULL,
        assessor_neighborhood text NULL,
        appraised_total integer NULL,
        "geometry" geometry NULL,
        number_of_apartments integer NULL,
        number_of_apartments_one_bedroom integer NULL,
        number_of_apartments_two_bedroom integer NULL,
        number_of_apartments_three_bedroom integer NULL,
        number_of_units integer NULL,
        number_of_stories integer NULL,
        number_of_garages integer NULL,
        number_of_carports integer NULL,
        number_of_full_baths integer NULL,
        number_of_half_baths integer NULL,
        ground_floor_area integer NULL,
        total_area integer NULL,
        total_living_area integer NULL,
        finished_basement_area integer NULL,
        avg_year_built integer NULL,
        number_of_buildings integer NULL,
        building_json jsonb NULL,
        cost_json jsonb NULL,
        struct_rcnld_with_oby numeric NULL,
        struct_rcnld_with_oby_and_land numeric NULL,
        tax_status text NULL,
        property_class text NULL,
        current_appraiser text NULL,
        is_active boolean NULL DEFAULT TRUE,
        created_at timestamptz NOT NULL DEFAULT now (),
        updated_at timestamptz NULL
    );


-- Purpose: Most common query pattern is filtering by parcel_id
-- Impact: 5-20x faster queries on active parcels
CREATE INDEX parcel_search_table_parcel_id_idx ON public.parcel_search_table (parcel_id)
WHERE
    is_active = TRUE;

-- Purpose: Support address-based searches (street_name + low_address_number + zip)
-- Column order: street_name (=), low_address_number (=), zip (=)
CREATE INDEX parcel_search_table_address_idx ON public.parcel_search_table (street_name, low_address_number, zip)
WHERE
    is_active = TRUE;

-- Purpose: Support searching by owner name
-- Uses GIN index for efficient text pattern matching
CREATE INDEX parcel_search_table_owner_name_idx ON public.parcel_search_table USING gin (owner_name gin_trgm_ops)
WHERE
    is_active = TRUE;



-- Purpose: Support filtering by geographic boundaries
CREATE INDEX parcel_search_table_geography_idx ON public.parcel_search_table (assessor_neighborhood)
WHERE
    is_active = TRUE;

-- Purpose: Support filtering by appraised values
CREATE INDEX parcel_search_table_appraised_total_idx ON public.parcel_search_table (appraised_total)
WHERE
    is_active = TRUE;

-- Purpose: Support filtering by current appraiser
CREATE INDEX parcel_search_table_current_appraiser_idx ON public.parcel_search_table (current_appraiser)
WHERE
    is_active = TRUE;

-- Purpose: Support filtering by condition field of cost_json
CREATE INDEX parcel_search_table_cost_json_condition_idx ON public.parcel_search_table USING gin (cost_json jsonb_path_ops)
WHERE
    is_active = TRUE;

-- Purpose: Support filtering by total living area
CREATE INDEX parcel_search_table_total_living_area_idx ON public.parcel_search_table (total_living_area)
WHERE
    is_active = TRUE;

-- Enable Row Level Security
ALTER TABLE public.parcel_search_table ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for parcel_search_table
-- Policy 1: Read access for users with parcel_search_table.read permission
CREATE POLICY parcel_search_table_select_policy ON public.parcel_search_table FOR
SELECT
    TO authenticated USING (
        public.authorize ('parcel_search_table.read')
    );

-- Policy 2: Insert access for users with parcel_search_table.write permission
CREATE POLICY parcel_search_table_insert_policy ON public.parcel_search_table FOR INSERT TO authenticated
WITH
    CHECK (
        public.authorize ('parcel_search_table.write')
    );

-- Policy 3: Update access for users with parcel_search_table.write permission
CREATE POLICY parcel_search_table_update_policy ON public.parcel_search_table FOR
UPDATE TO authenticated USING (
    public.authorize ('parcel_search_table.write')
)
WITH
    CHECK (
        public.authorize ('parcel_search_table.write')
    );

-- Policy 4: Delete access for users with parcel_search_table.delete permission
CREATE POLICY parcel_search_table_delete_policy ON public.parcel_search_table FOR DELETE TO authenticated USING (
    public.authorize ('parcel_search_table.delete')
);

-- Add trigger for updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_parcel_search_table_updated_at ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER parcel_search_table_updated_at_trigger
    BEFORE UPDATE ON public.parcel_search_table
    FOR EACH ROW
    EXECUTE FUNCTION public.update_parcel_search_table_updated_at ();
