CREATE TABLE
    IF NOT EXISTS public.sales_summary (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id INTEGER,
        sale_price INTEGER,
        sale_date DATE,
        sale_type TEXT,
        field_review_date DATE,
        number_of_apartments INTEGER,
        number_of_apartments_one_bed INTEGER,
        number_of_apartments_two_bed INTEGER,
        number_of_apartments_three_bed INTEGER,
        number_of_units INTEGER,
        number_of_stories INTEGER,
        number_of_garages INTEGER,
        number_of_carports INTEGER,
        number_of_full_baths INTEGER,
        number_of_half_baths INTEGER,
        ground_floor_area INTEGER,
        total_area INTEGER,
        total_living_area INTEGER,
        finished_basement_area INTEGER,
        avg_year_built INTEGER,
        number_of_buildings INTEGER,
        building_json JSONB,
        struct_rcnld_with_oby INTEGER,
        struct_rcnld_with_oby_and_land INTEGER,
        res_cost_json JSONB,
        land_area INTEGER,
        number_of_parcels INTEGER,
        centroid_x NUMERIC,
        centroid_y NUMERIC,
        parcels_json JSONB,
        current_appraised_ratio NUMERIC,
        cost_with_land_ratio NUMERIC,
        appraised_land INTEGER,
        appraised_improvements INTEGER,
        appraised_total INTEGER
    );

CREATE INDEX IF NOT EXISTS sales_summary_sale_price_idx ON public.sales_summary (sale_price);

CREATE INDEX IF NOT EXISTS sales_summary_sale_date_idx ON public.sales_summary (sale_date);

CREATE INDEX IF NOT EXISTS sales_summary_total_area_idx ON public.sales_summary (total_area);

CREATE INDEX IF NOT EXISTS sales_summary_total_living_area_idx ON public.sales_summary (total_living_area);

CREATE INDEX IF NOT EXISTS sales_summary_building_json_gin_idx ON public.sales_summary USING GIN (building_json);

CREATE INDEX IF NOT EXISTS sales_summary_res_cost_json_gin_idx ON public.sales_summary USING GIN (res_cost_json);

CREATE INDEX IF NOT EXISTS sales_summary_centroid_x_idx ON public.sales_summary (centroid_x);

CREATE INDEX IF NOT EXISTS sales_summary_centroid_y_idx ON public.sales_summary (centroid_y);

CREATE INDEX IF NOT EXISTS sales_summary_parcels_json_gin_idx ON public.sales_summary USING GIN (parcels_json);

CREATE INDEX IF NOT EXISTS sales_summary_cost_with_land_ratio_idx ON public.sales_summary (cost_with_land_ratio);

CREATE INDEX IF NOT EXISTS sales_summary_current_appraised_ratio_idx ON public.sales_summary (current_appraised_ratio);

-- Enable Row Level Security
ALTER TABLE public.sales_summary ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for sales_summary
-- Policy 1: Read access for users with sales_summary.read permission
CREATE POLICY sales_summary_select_policy ON public.sales_summary FOR
SELECT
    TO authenticated USING (public.authorize ('sales_summary.read'));

-- Policy 2: Insert access for users with sales_summary.write permission
CREATE POLICY sales_summary_insert_policy ON public.sales_summary FOR INSERT TO authenticated
WITH
    CHECK (public.authorize ('sales_summary.write'));

-- Policy 3: Update access for users with sales_summary.write permission
CREATE POLICY sales_summary_update_policy ON public.sales_summary FOR
UPDATE TO authenticated USING (public.authorize ('sales_summary.write'))
WITH
    CHECK (public.authorize ('sales_summary.write'));

-- Policy 4: Delete access for users with sales_summary.delete permission
CREATE POLICY sales_summary_delete_policy ON public.sales_summary FOR DELETE TO authenticated USING (public.authorize ('sales_summary.delete'));