-- Create neighborhoods_geom table with PostGIS geometry
-- This table replaces the jsonb polygon column with a proper PostGIS Polygon geometry
CREATE TABLE
    IF NOT EXISTS public.assessor_neighborhoods (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        "group" text,
        geom geometry (Polygon, 4326) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now ()
    );

-- Create indexes
CREATE INDEX IF NOT EXISTS assessor_neighborhoods_geom_idx ON public.assessor_neighborhoods USING GIST (geom);

COMMENT ON TABLE public.assessor_neighborhoods IS 'Assessor Neighborhoods with PostGIS geometry polygons in WGS84 (EPSG:4326)';

COMMENT ON COLUMN public.assessor_neighborhoods.geom IS 'Polygon geometry in WGS84 (lat/lng)';

-- Enable RLS
ALTER TABLE public.assessor_neighborhoods ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view all neighborhoods
CREATE POLICY "Users can view neighborhoods" ON public.assessor_neighborhoods FOR
SELECT
    TO authenticated USING (true);

-- RLS Policy: Only users with neighborhoods.manage can insert/update/delete neighborhoods
CREATE POLICY "Only users with assessor_neighborhoods.manage can modify neighborhoods" ON public.assessor_neighborhoods FOR ALL TO authenticated USING (authorize ('neighborhoods.manage'))
WITH
    CHECK (authorize ('assessor_neighborhoods.manage'));